// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
export const VERSION = '0.0.0'; // This value will be overwritten by webpack
export const DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
